### PR TITLE
source_id -- add 'AWI-ESM-1-REcoM'

### PR DESCRIPTION
**Pull request by chrisdane**
Hi

Is it possible to add this `source_id` to the repository? The data is currently cmorized with support from @sol1105 from DKRZ and the cmorized data can be linked to ESGF from there. Hence I have put `cohort: Registered` and will inform you when this process is finished. For the cmorizing process, however, we would need this `source_id`.

Thanks a lot and kind regards,
Chris

ps: I have no idea why my vi modified the last line, sorry.

### CODE REVIEW

**Comment by chrisdane** [comment]
Hi Paul

> if you are running CMIP6-specified experiments using the model, then this could be added. 

Yes
> I presume you also plan to publish these simulations into the CMIP6 ESGF project at DKRZ?

Yes

Thanks!

**Comment by durack1** [comment]
@chrisdane ok good enough for me. I'll get this in the queue for addition, and this should propagate across to the [PCMDI/cmip6-cmor-tables/Tables/CMIP6_CV.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/main/Tables/CMIP6_CV.json) overnight, which should simplify your config to run CMOR

@matthew-mizielinski @mauzey1 @taylor13 @wolfiex ping

**Comment by durack1** [comment]
@chrisdane that registration is now complete, take a peek at [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and other pages to see your registration live. Just a query, other AWI models are denoted with a period demarker version e.g. 1.1, 1.2, etc. Is the 1 in your registration a little light, so would you prefer a "*1.2 REcoM" instead?

And while I have you, we have an open issue from years ago, related to the `AWI-CM-2-1-LR` publication (see #1116). Should this non-existent model be deregistered? It seems like with no activity for years, it's time to cleanup and close out that remaining issue

**Comment by chrisdane** [comment]
Thanks a lot Paul!

**Comment by durack1** [comment]
No problem. @christian-stepanek, is it time to deregister `AWI-CM-2-1-LR`, or is work to publish simulations still ongoing? Feel free to reply in #1116

**Comment by durack1** [comment]
@chrisdane please ping this thread when the `AWI-ESM-1-RecoM` data is live on https://esgf-data.dkrz.de/search/cmip6-dkrz/ - we have one final tweak, which is toggling the "Registered" status to "Published"

**Pull request closed without merging**
