### PR TITLE
Register source_id IPSL-CM6A-ATM-ICO series

### PR DESCRIPTION
**Pull request by matthew-mizielinski**
Covers #1043, #1044, #1045, #1046 : The addition of LR, MR, HR and VHR resolution variants of IPSL-CM6A-ATM-ICO

### CODE REVIEW

**Comment by durack1** [comment]
@matthew-mizielinski thanks for this, I had a more philosophical question whether we wanted to add these models to CMIP6 (is the project closed), it seems that at least one has a resolution of 250 km, which seems like it misses the HighResMIP boat

@taylor13

**Comment by matthew-mizielinski** [comment]
> @matthew-mizielinski thanks for this, I had a more philosophical question whether we wanted to add these models to CMIP6 (is the project closed), it seems that at least one has a resolution of 250 km, which seems like it misses the HighResMIP boat
> 
> @taylor13

Good point -- this hadn't occurred to me. I'll hold pending further discussion

**Review by durack1 — APPROVED** [review]
@matthew-mizielinski looks great

**Comment by durack1** [comment]
Fix #1043 #1044 #1045 #1046

**Pull request merged**
